import "@/lib/polyfill-localstorage";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "sonner";
import NuqsClientAdapter from "@/components/nuqs-client-adapter";

const inter = Inter({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<NuqsClientAdapter>
			<TRPCReactProvider>
				<html lang="en">
					<body className={`${inter.className} antialiased`}>
						<Toaster />
						{children}
					</body>
				</html>
			</TRPCReactProvider>
		</NuqsClientAdapter>
	);
}
